version: '{build}'

# FIXME(NH): Workaround for https://github.com/appveyor/ci/issues/1202
image: Previous Visual Studio 2015

clone_depth: 100

configuration:
  - Debug
  - Release

cache:
  - _deps -> appveyor.yml, .appveyor_setup.sh

environment:
  CTEST_PARALLEL_LEVEL: '%NUMBER_OF_PROCESSORS%'
  CTEST_OUTPUT_ON_FAILURE: '1'

  matrix:
    - COMPILER: clang-39
      TARGET: x86_64-pc-windows-msvc19.0.0
      PATH: '%APPVEYOR_BUILD_FOLDER%\_deps\bin;%PATH%'
      CC: clang-cl
      CXX: clang-cl
      VS: '"%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'

    - COMPILER: mingw-w64-53
      TARGET: i686-pc-windows-gnu
      PATH: '%APPVEYOR_BUILD_FOLDER%\_deps\bin;%PATH%;C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
      CC: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin\gcc.exe'
      CXX: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin\g++.exe'

    - COMPILER: msvc-19
      TARGET: x86_64-pc-windows-msvc19.0.0
      PATH: '%APPVEYOR_BUILD_FOLDER%\_deps\bin;%PATH%'
      CC: cl
      CXX: cl
      VS: '"%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'

    - COMPILER: msvc-18
      TARGET: x86_64-pc-windows-msvc18.0.0
      PATH: '%APPVEYOR_BUILD_FOLDER%\_deps\bin;%PATH%'
      CC: cl
      CXX: cl
      VS: '"%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64'

    - COMPILER: msvc-16
      TARGET: x86_64-pc-windows-msvc16.0.0
      PATH: '%APPVEYOR_BUILD_FOLDER%\_deps\bin;%PATH%'
      CC: cl
      CXX: cl
      VS: '"%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
      BOOST_INCLUDEDIR: '%APPVEYOR_BUILD_FOLDER%\_deps\boost_1_56_0-msvc-10.0-64'
      BOOST_LIBRARYDIR: '%APPVEYOR_BUILD_FOLDER%\_deps\boost_1_56_0-msvc-10.0-64\lib64-msvc-10.0'
      EXTRA_CMAKE_ARGS: '-DBoost_USE_STATIC_LIBS=1 -DBENCHMARK_ENABLE_CXX11=0'

install:
  - sh .appveyor_setup.sh

before_build:
  - if defined VS ( call %VS% )

build_script:
  - mkdir _build
  - cd _build

  - cmake -GNinja -DCMAKE_BUILD_TYPE=%CONFIGURATION% %EXTRA_CMAKE_ARGS% ..
  - cmake --build .
  - cmake --build . --target install

  # Once more, with feeling.
  - cmake -DBUILD_SHARED_LIBS=1 ..
  - cmake --build .
  - cmake --build . --target install

test_script:
  - ctest --timeout 300

artifacts:
  - path: '_build/CMakeFiles/*.log'
    name: logs
  - path: '_build/Testing/**/*.xml'
    name: test_results

